apiVersion: apps/v1
kind: Deployment
metadata:
  name: cipproxy-api-deployment
  namespace: app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cipproxy-api
  template:
    metadata:
      labels:
        app: cipproxy-api
    spec:
      containers:
      - name: cipproxy-api
        image: dockub.coralpay.com/cipproxy:#{image-tag}#
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "200M"
            cpu: "100m"    
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
            - name: keys
              mountPath: /app/keys
        envFrom:
        - configMapRef:
            name: cipproxy
        - configMapRef:
            name: timezone
      imagePullSecrets:
        - name: docker-cred
      volumes:
        - name: keys
          secret:
            secretName: cipproxy

---

apiVersion: v1
kind: Service
metadata:
  name: cipproxy-api-service
  namespace: app-prod
spec:
  type: ClusterIP
  selector:
    app: cipproxy-api
  ports:
  - port: 9091
    targetPort: 80