apiVersion: apps/v1
kind: Deployment
metadata:
  name: cipproxy-api-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cipproxy-api
  template:
    metadata:
      labels:
        app: cipproxy-api
    spec:
      containers:
      - name: cipproxy-api
        image: dockub.coralpay.com/cipproxy:#{image-tag}#
        resources:
          limits:
            memory: "228Mi"
            cpu: "200m"
          requests:
            memory: "200M"
            cpu: "100m"  
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: TZ
            value: Africa/Lagos
          - name: ConnectionStrings__ConnStr
            valueFrom:
              secretKeyRef:
                name: dbconnection
                key: cverge
      imagePullSecrets:
        - name: docker-cred
---

apiVersion: v1
kind: Service
metadata:
  name: cipproxy-api-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: cipproxy-api
  ports:
  - port: 5903
    targetPort: 80