apiVersion: apps/v1
kind: Deployment
metadata:
  name: etranzactproxy-api-deployment
  namespace: app-stg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etranzactproxy-api
  template:
    metadata:
      labels:
        app: etranzactproxy-api
    spec:
      containers:
      - name: etranzactproxy-api
        image: dockub.coralpay.com/etranzactproxy:#{image-tag}#
        resources:
          limits:
            memory: "228Mi"
            cpu: "200m"
          requests:
            memory: "200M"
            cpu: "100m"  
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: BankCodes
            value: '[{"BankName":"AccessBank","NibssCode":"000014","CbnCode":"044"},{"BankName":"DiamondBank","NibssCode":"000005","CbnCode":"063"},{"BankName":"Ecobank","NibssCode":"000010","CbnCode":"050"},{"BankName":"EnterpriseBank","NibssCode":"000019","CbnCode":"084"},{"BankName":"FidelityBank","NibssCode":"000007","CbnCode":"070"},{"BankName":"FirstBankofNigeria","NibssCode":"000016","CbnCode":"011"},{"BankName":"FirstCityMonumentBank","NibssCode":"000003","CbnCode":"214"},{"BankName":"GuarantyTrustBank","NibssCode":"000013","CbnCode":"058"},{"BankName":"HeritageBank","NibssCode":"000020","CbnCode":"030"},{"BankName":"JaizBank","NibssCode":"000006","CbnCode":"301"},{"BankName":"KeystoneBank","NibssCode":"000002","CbnCode":"082"},{"BankName":"PolarisBank","NibssCode":"000008","CbnCode":"076"},{"BankName":"StanbicIBTC","NibssCode":"000012","CbnCode":"039"},{"BankName":"SterlingBank","NibssCode":"000001","CbnCode":"232"},{"BankName":"UnionBank","NibssCode":"000018","CbnCode":"032"},{"BankName":"UnitedBankforAfrica","NibssCode":"000004","CbnCode":"033"},{"BankName":"UnityBank","NibssCode":"000011","CbnCode":"215"},{"BankName":"WEMABank","NibssCode":"000017","CbnCode":"035"},{"BankName":"ZenithBank","NibssCode":"000015","CbnCode":"057"}]'
        envFrom:
        - secretRef:
            name: etranzactproxy
        - configMapRef:
            name: etranzactproxy
        - configMapRef:
            name: timezone
      imagePullSecrets:
        - name: docker-cred
---

apiVersion: v1
kind: Service
metadata:
  name: etranzactproxy-api-service
  namespace: app-stg
spec:
  type: ClusterIP
  selector:
    app: etranzactproxy-api
  ports:
  - port: 8080
    targetPort: 8080