//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NipService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mtn.com/aggregator/nibss/", ConfigurationName="NipService.NibssPort")]
    public interface NibssPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(NipService.fundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.accountunblockResponse> accountunblockAsync(NipService.accountunblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(NipService.fundtransfersingleitem_ddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(NipService.fundtransferAdvice_ddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(NipService.fundtransferAdvice_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.mandateadviceResponse> mandateadviceAsync(NipService.mandateadviceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.amountunblockResponse> amountunblockAsync(NipService.amountunblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.financialinstitutionlistResponse> financialinstitutionlistAsync(NipService.financialinstitutionlistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.balanceenquiryResponse> balanceenquiryAsync(NipService.balanceenquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.nameenquirysingleitemResponse> nameenquirysingleitemAsync(NipService.nameenquirysingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.amountblockResponse> amountblockAsync(NipService.amountblockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NipService.accountblockResponse> accountblockAsync(NipService.accountblockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_dcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_dcRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransfersingleitem_dcRequest1;
        
        public fundtransfersingleitem_dcRequest()
        {
        }
        
        public fundtransfersingleitem_dcRequest(string fundtransfersingleitem_dcRequest1)
        {
            this.fundtransfersingleitem_dcRequest1 = fundtransfersingleitem_dcRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_dcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_dcResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransfersingleitem_dcResponse1;
        
        public fundtransfersingleitem_dcResponse()
        {
        }
        
        public fundtransfersingleitem_dcResponse(string fundtransfersingleitem_dcResponse1)
        {
            this.fundtransfersingleitem_dcResponse1 = fundtransfersingleitem_dcResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountunblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountunblockRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string accountunblockRequest1;
        
        public accountunblockRequest()
        {
        }
        
        public accountunblockRequest(string accountunblockRequest1)
        {
            this.accountunblockRequest1 = accountunblockRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountunblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountunblockResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string accountunblockResponse1;
        
        public accountunblockResponse()
        {
        }
        
        public accountunblockResponse(string accountunblockResponse1)
        {
            this.accountunblockResponse1 = accountunblockResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_ddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_ddRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransfersingleitem_ddRequest1;
        
        public fundtransfersingleitem_ddRequest()
        {
        }
        
        public fundtransfersingleitem_ddRequest(string fundtransfersingleitem_ddRequest1)
        {
            this.fundtransfersingleitem_ddRequest1 = fundtransfersingleitem_ddRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransfersingleitem_ddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransfersingleitem_ddResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransfersingleitem_ddResponse1;
        
        public fundtransfersingleitem_ddResponse()
        {
        }
        
        public fundtransfersingleitem_ddResponse(string fundtransfersingleitem_ddResponse1)
        {
            this.fundtransfersingleitem_ddResponse1 = fundtransfersingleitem_ddResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_ddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_ddRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransferAdvice_ddRequest1;
        
        public fundtransferAdvice_ddRequest()
        {
        }
        
        public fundtransferAdvice_ddRequest(string fundtransferAdvice_ddRequest1)
        {
            this.fundtransferAdvice_ddRequest1 = fundtransferAdvice_ddRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_ddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_ddResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransferAdvice_ddResponse1;
        
        public fundtransferAdvice_ddResponse()
        {
        }
        
        public fundtransferAdvice_ddResponse(string fundtransferAdvice_ddResponse1)
        {
            this.fundtransferAdvice_ddResponse1 = fundtransferAdvice_ddResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_dcRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_dcRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransferAdvice_dcRequest1;
        
        public fundtransferAdvice_dcRequest()
        {
        }
        
        public fundtransferAdvice_dcRequest(string fundtransferAdvice_dcRequest1)
        {
            this.fundtransferAdvice_dcRequest1 = fundtransferAdvice_dcRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fundtransferAdvice_dcResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fundtransferAdvice_dcResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string fundtransferAdvice_dcResponse1;
        
        public fundtransferAdvice_dcResponse()
        {
        }
        
        public fundtransferAdvice_dcResponse(string fundtransferAdvice_dcResponse1)
        {
            this.fundtransferAdvice_dcResponse1 = fundtransferAdvice_dcResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mandateadviceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mandateadviceRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string mandateadviceRequest1;
        
        public mandateadviceRequest()
        {
        }
        
        public mandateadviceRequest(string mandateadviceRequest1)
        {
            this.mandateadviceRequest1 = mandateadviceRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mandateadviceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mandateadviceResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string mandateadviceResponse1;
        
        public mandateadviceResponse()
        {
        }
        
        public mandateadviceResponse(string mandateadviceResponse1)
        {
            this.mandateadviceResponse1 = mandateadviceResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountunblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountunblockRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string amountunblockRequest1;
        
        public amountunblockRequest()
        {
        }
        
        public amountunblockRequest(string amountunblockRequest1)
        {
            this.amountunblockRequest1 = amountunblockRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountunblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountunblockResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string amountunblockResponse1;
        
        public amountunblockResponse()
        {
        }
        
        public amountunblockResponse(string amountunblockResponse1)
        {
            this.amountunblockResponse1 = amountunblockResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class financialinstitutionlistRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="financialinstitutionlistRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string financialinstitutionlistRequest1;
        
        public financialinstitutionlistRequest()
        {
        }
        
        public financialinstitutionlistRequest(string financialinstitutionlistRequest1)
        {
            this.financialinstitutionlistRequest1 = financialinstitutionlistRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class financialinstitutionlistResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="financialinstitutionlistResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string financialinstitutionlistResponse1;
        
        public financialinstitutionlistResponse()
        {
        }
        
        public financialinstitutionlistResponse(string financialinstitutionlistResponse1)
        {
            this.financialinstitutionlistResponse1 = financialinstitutionlistResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class balanceenquiryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="balanceenquiryRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string balanceenquiryRequest1;
        
        public balanceenquiryRequest()
        {
        }
        
        public balanceenquiryRequest(string balanceenquiryRequest1)
        {
            this.balanceenquiryRequest1 = balanceenquiryRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class balanceenquiryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="balanceenquiryResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string balanceenquiryResponse1;
        
        public balanceenquiryResponse()
        {
        }
        
        public balanceenquiryResponse(string balanceenquiryResponse1)
        {
            this.balanceenquiryResponse1 = balanceenquiryResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nameenquirysingleitemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nameenquirysingleitemRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string nameenquirysingleitemRequest1;
        
        public nameenquirysingleitemRequest()
        {
        }
        
        public nameenquirysingleitemRequest(string nameenquirysingleitemRequest1)
        {
            this.nameenquirysingleitemRequest1 = nameenquirysingleitemRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nameenquirysingleitemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nameenquirysingleitemResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string nameenquirysingleitemResponse1;
        
        public nameenquirysingleitemResponse()
        {
        }
        
        public nameenquirysingleitemResponse(string nameenquirysingleitemResponse1)
        {
            this.nameenquirysingleitemResponse1 = nameenquirysingleitemResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountblockRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string amountblockRequest1;
        
        public amountblockRequest()
        {
        }
        
        public amountblockRequest(string amountblockRequest1)
        {
            this.amountblockRequest1 = amountblockRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class amountblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="amountblockResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string amountblockResponse1;
        
        public amountblockResponse()
        {
        }
        
        public amountblockResponse(string amountblockResponse1)
        {
            this.amountblockResponse1 = amountblockResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountblockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountblockRequest", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string accountblockRequest1;
        
        public accountblockRequest()
        {
        }
        
        public accountblockRequest(string accountblockRequest1)
        {
            this.accountblockRequest1 = accountblockRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class accountblockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="accountblockResponse", Namespace="http://www.mtn.com/aggregator/nibss/", Order=0)]
        public string accountblockResponse1;
        
        public accountblockResponse()
        {
        }
        
        public accountblockResponse(string accountblockResponse1)
        {
            this.accountblockResponse1 = accountblockResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface NibssPortChannel : NipService.NibssPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class NibssPortClient : System.ServiceModel.ClientBase<NipService.NibssPort>, NipService.NibssPort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NibssPortClient() : 
                base(NibssPortClient.GetDefaultBinding(), NibssPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NibssPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NibssPortClient(EndpointConfiguration endpointConfiguration) : 
                base(NibssPortClient.GetBindingForEndpoint(endpointConfiguration), NibssPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NibssPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NibssPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NibssPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NibssPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NibssPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.fundtransfersingleitem_dcResponse> NipService.NibssPort.fundtransfersingleitem_dcAsync(NipService.fundtransfersingleitem_dcRequest request)
        {
            return base.Channel.fundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.fundtransfersingleitem_dcResponse> fundtransfersingleitem_dcAsync(string fundtransfersingleitem_dcRequest1)
        {
            NipService.fundtransfersingleitem_dcRequest inValue = new NipService.fundtransfersingleitem_dcRequest();
            inValue.fundtransfersingleitem_dcRequest1 = fundtransfersingleitem_dcRequest1;
            return ((NipService.NibssPort)(this)).fundtransfersingleitem_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.accountunblockResponse> NipService.NibssPort.accountunblockAsync(NipService.accountunblockRequest request)
        {
            return base.Channel.accountunblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.accountunblockResponse> accountunblockAsync(string accountunblockRequest1)
        {
            NipService.accountunblockRequest inValue = new NipService.accountunblockRequest();
            inValue.accountunblockRequest1 = accountunblockRequest1;
            return ((NipService.NibssPort)(this)).accountunblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.fundtransfersingleitem_ddResponse> NipService.NibssPort.fundtransfersingleitem_ddAsync(NipService.fundtransfersingleitem_ddRequest request)
        {
            return base.Channel.fundtransfersingleitem_ddAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.fundtransfersingleitem_ddResponse> fundtransfersingleitem_ddAsync(string fundtransfersingleitem_ddRequest1)
        {
            NipService.fundtransfersingleitem_ddRequest inValue = new NipService.fundtransfersingleitem_ddRequest();
            inValue.fundtransfersingleitem_ddRequest1 = fundtransfersingleitem_ddRequest1;
            return ((NipService.NibssPort)(this)).fundtransfersingleitem_ddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.fundtransferAdvice_ddResponse> NipService.NibssPort.fundtransferAdvice_ddAsync(NipService.fundtransferAdvice_ddRequest request)
        {
            return base.Channel.fundtransferAdvice_ddAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.fundtransferAdvice_ddResponse> fundtransferAdvice_ddAsync(string fundtransferAdvice_ddRequest1)
        {
            NipService.fundtransferAdvice_ddRequest inValue = new NipService.fundtransferAdvice_ddRequest();
            inValue.fundtransferAdvice_ddRequest1 = fundtransferAdvice_ddRequest1;
            return ((NipService.NibssPort)(this)).fundtransferAdvice_ddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.fundtransferAdvice_dcResponse> NipService.NibssPort.fundtransferAdvice_dcAsync(NipService.fundtransferAdvice_dcRequest request)
        {
            return base.Channel.fundtransferAdvice_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.fundtransferAdvice_dcResponse> fundtransferAdvice_dcAsync(string fundtransferAdvice_dcRequest1)
        {
            NipService.fundtransferAdvice_dcRequest inValue = new NipService.fundtransferAdvice_dcRequest();
            inValue.fundtransferAdvice_dcRequest1 = fundtransferAdvice_dcRequest1;
            return ((NipService.NibssPort)(this)).fundtransferAdvice_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.mandateadviceResponse> NipService.NibssPort.mandateadviceAsync(NipService.mandateadviceRequest request)
        {
            return base.Channel.mandateadviceAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.mandateadviceResponse> mandateadviceAsync(string mandateadviceRequest1)
        {
            NipService.mandateadviceRequest inValue = new NipService.mandateadviceRequest();
            inValue.mandateadviceRequest1 = mandateadviceRequest1;
            return ((NipService.NibssPort)(this)).mandateadviceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.amountunblockResponse> NipService.NibssPort.amountunblockAsync(NipService.amountunblockRequest request)
        {
            return base.Channel.amountunblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.amountunblockResponse> amountunblockAsync(string amountunblockRequest1)
        {
            NipService.amountunblockRequest inValue = new NipService.amountunblockRequest();
            inValue.amountunblockRequest1 = amountunblockRequest1;
            return ((NipService.NibssPort)(this)).amountunblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.financialinstitutionlistResponse> NipService.NibssPort.financialinstitutionlistAsync(NipService.financialinstitutionlistRequest request)
        {
            return base.Channel.financialinstitutionlistAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.financialinstitutionlistResponse> financialinstitutionlistAsync(string financialinstitutionlistRequest1)
        {
            NipService.financialinstitutionlistRequest inValue = new NipService.financialinstitutionlistRequest();
            inValue.financialinstitutionlistRequest1 = financialinstitutionlistRequest1;
            return ((NipService.NibssPort)(this)).financialinstitutionlistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.balanceenquiryResponse> NipService.NibssPort.balanceenquiryAsync(NipService.balanceenquiryRequest request)
        {
            return base.Channel.balanceenquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.balanceenquiryResponse> balanceenquiryAsync(string balanceenquiryRequest1)
        {
            NipService.balanceenquiryRequest inValue = new NipService.balanceenquiryRequest();
            inValue.balanceenquiryRequest1 = balanceenquiryRequest1;
            return ((NipService.NibssPort)(this)).balanceenquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.nameenquirysingleitemResponse> NipService.NibssPort.nameenquirysingleitemAsync(NipService.nameenquirysingleitemRequest request)
        {
            return base.Channel.nameenquirysingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.nameenquirysingleitemResponse> nameenquirysingleitemAsync(string nameenquirysingleitemRequest1)
        {
            NipService.nameenquirysingleitemRequest inValue = new NipService.nameenquirysingleitemRequest();
            inValue.nameenquirysingleitemRequest1 = nameenquirysingleitemRequest1;
            return ((NipService.NibssPort)(this)).nameenquirysingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.amountblockResponse> NipService.NibssPort.amountblockAsync(NipService.amountblockRequest request)
        {
            return base.Channel.amountblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.amountblockResponse> amountblockAsync(string amountblockRequest1)
        {
            NipService.amountblockRequest inValue = new NipService.amountblockRequest();
            inValue.amountblockRequest1 = amountblockRequest1;
            return ((NipService.NibssPort)(this)).amountblockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipService.accountblockResponse> NipService.NibssPort.accountblockAsync(NipService.accountblockRequest request)
        {
            return base.Channel.accountblockAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipService.accountblockResponse> accountblockAsync(string accountblockRequest1)
        {
            NipService.accountblockRequest inValue = new NipService.accountblockRequest();
            inValue.accountblockRequest1 = accountblockRequest1;
            return ((NipService.NibssPort)(this)).accountblockAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NibssPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NibssPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://41.220.77.13/nibss/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NibssPortClient.GetBindingForEndpoint(EndpointConfiguration.NibssPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NibssPortClient.GetEndpointAddress(EndpointConfiguration.NibssPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            NibssPortSoap11,
        }
    }
}
