name: Nextgen-MomoIPRouter

on:
  push:
    branches:
      - coralpayupdates_dev
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/coralpayupdates_dev'  # Apply condition at the job level
    strategy:
      matrix:
        dockerfile: [
          # "arca.Dockerfile",
          # "cipproxy.dockerfile",
          # "etranzactproxy.dockerfile", 
          # "jobs.dockerfile",
          # "momo-switchrequery.dockerfile",
          # "momoswitch.dockerfile",
          # "momoswitchanalysis.Dockerfile",
          "nipinwardproxy.dockerfile",
          "nipoutward.dockerfile",
        #  "portal2.dockerfile",
          "remitaproxy.Dockerfile"
        ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ojtkgsbharb01.mtn.com.ng/nextgen_momoiprouter/nextgen_momoiprouter-nonportal
          username: ${{ secrets.HARBOR_UNAME }}
          password: ${{ secrets.HARBOR_PASSWD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ojtkgsbharb01.mtn.com.ng/nextgen_momoiprouter/nextgen_momoiprouter-nonportal:${{ steps.short-sha.outputs.sha }}

    #   - name: Checkout Helm Repository
    #     uses: actions/checkout@v2
    #     with:
    #       ref: dev
    #       repository: MTNNigeria/Helm-Charts
    #       token: ${{ secrets.my_pat }}
    #     path: helm-repo  # Ensure it doesn't overwrite the main repo

    #   - name: Update Helm Chart
    #     run: |
    #       IMAGE_TAG=${{ steps.short-sha.outputs.sha }}
    #       yq e '.image.version = "'$IMAGE_TAG'"' -i helm-repo/nextgen_momoiprouter/frontend/charts/helm-example/values.yaml
    #       cd helm-repo
    #       git config --global user.name 'gkhhgcl'
    #       git config --global user.email "girish.kumar@hhgcl.com"
    #       git add .
    #       git commit -m "Updated values.yaml file"
    #       git push origin dev