name: Nextgen-MomoIPRouter

on:
  push:
    branches:
      - coralpayupdates_dev
      - main
jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        if: github.ref == 'refs/heads/coralpayupdates_dev'
        uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      - name: Login to dev image repository
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/coralpayupdates_dev'
        env:
          REGISTRY: ojtkgsbharb01.mtn.com.ng/nextgen_momoiprouter/nextgen_momoiprouter-portal
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_UNAME }}
          password: ${{ secrets.HARBOR_PASSWD }}

      - name: dev Build and push
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/coralpayupdates_dev'
        env:
          REGISTRY: ojtkgsbharb01.mtn.com.ng/nextgen_momoiprouter/nextgen_momoiprouter-portal
          IMAGE_TAG: ${{ env.SHA }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}

      # - name: Check out dev helm repo
        ## if: github.ref == 'refs/heads/coralpayupdates_dev'
      #   uses: actions/checkout@v2
      #   with:
      #     ref: dev
      #     repository: MTNNigeria/Helm-Charts
      #     token: ${{ secrets.my_pat }}

      # - name: Update dev helm
      ##   if: github.ref == 'refs/heads/coralpayupdates_dev'
      #   env:
      #     IMAGE_TAG: ${{ env.SHA }}
      #   run: |
      #     yq e '.image.version = "'$IMAGE_TAG'"' -i /export/home/dmsb_girish/NextGen-UI/_work/NextGen-UI/NextGen-UI/nextgenui/frontend/charts/helm-example/values.yaml
      #     git config --global user.name 'gkhhgcl'
      #     git config --global user.email "girish.kumar@hhgcl.com"
      #     git add .
      #     git commit -m "updated values.yml file"
      #     echo "Done.."
      #     git push origin dev