name: Nextgen-MomoIPRouter

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout
        if: github.ref == 'refs/heads/dev'
        uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      - name: Login to dev image repository
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/dev'
        env:
          REGISTRY: ojtkgsbharb01.mtn.com.ng/router/router-ip
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_UNAME }}
          password: ${{ secrets.HARBOR_PASSWD }}

      - name: dev Build and push
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/dev'
        env:
          REGISTRY: ojtkgsbharb01.mtn.com.ng/router/router-ip
          IMAGE_TAG: ${{ env.SHA }}
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}:${{ env.IMAGE_TAG }}